CREATE DATABASE POST_MINI;
USE POST_MINI;

CREATE TABLE EMPLOYEE
(
	EMP_NUM INT NOT NULL,
    EMP_DOB DATE,
    EMP_TITLE CHAR(3),
    EMP_NAME VARCHAR(45),
    HIRE_DATE DATE,
    EMP_PHONE VARCHAR(12),
	PRIMARY KEY (EMP_NUM)
);

CREATE TABLE STUDENT
(
	STUD_ID INT NOT NULL,
    STUD_NAME VARCHAR(45),
    STUD_COLLEGE VARCHAR(10),
    STUD_PHONE VARCHAR(12),
    PRIMARY KEY (STUD_ID)
);

CREATE TABLE COURIER
(
	DRIVER_CODE VARCHAR(8) NOT NULL,
    DRIVER_NAME VARCHAR(25),
    DRIVER_PHONE VARCHAR(12),
    COURIER_NAME VARCHAR(15),
    PRIMARY KEY (DRIVER_CODE)
);

CREATE TABLE PARCEL
(
	TRACKING_NO VARCHAR(20) NOT NULL,
    PARCEL_SIZE CHAR(1),
    PARCEL_PRICE DECIMAL(4,2),
    ARRIVE_DATE DATE,
    PARCEL_LOCATION VARCHAR(10),
    EMP_NUM INT NOT NULL,
    STUD_ID INT NOT NULL,
    DRIVER_CODE VARCHAR(8) NOT NULL,
	COLLECTED CHAR(3),
    PRIMARY KEY (TRACKING_NO),
    FOREIGN KEY (EMP_NUM) REFERENCES EMPLOYEE(EMP_NUM),
	FOREIGN KEY (STUD_ID) REFERENCES STUDENT(STUD_ID),
    FOREIGN KEY (DRIVER_CODE) REFERENCES COURIER(DRIVER_CODE)
);

CREATE TABLE PAYMENT
(
	TRANSACTION_NO INT NOT NULL,
    PAID_PRICE DECIMAL(4,2),
    PAYMENT_DATE DATE,
    STUD_ID INT NOT NULL,
    EMP_NUM INT NOT NULL,
    PRIMARY KEY (TRANSACTION_NO),
    FOREIGN KEY (STUD_ID) REFERENCES STUDENT(STUD_ID),
    FOREIGN KEY (EMP_NUM) REFERENCES EMPLOYEE(EMP_NUM)    
);

COMMIT;